/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 14/01/2022 16:54:09
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            8000000
#define MX_EXTERNAL_CLOCK_VALUE                 48000
#define MX_SYSCLKFreq_VALUE                     64000000
#define MX_HCLKFreq_Value                       64000000
#define MX_FCLKCortexFreq_Value                 64000000
#define MX_CortexFreq_Value                     64000000
#define MX_AHBFreq_Value                        64000000
#define MX_APBFreq_Value                        64000000
#define MX_CECFreq_Value                        4000000
#define MX_I2S1Freq_Value                       64000000
#define MX_PWRFreq_Value                        64000000
#define MX_RTCFreq_Value                        32000
#define MX_USBFreq_Value                        16000000
#define MX_WatchDogFreq_Value                   32000
#define MX_MCO1PinFreq_Value                    64000000
#define MX_TIM1Freq_Value                       64000000
#define MX_LPUART1Freq_Value                    4000000
#define MX_TIM15Freq_Value                      64000000
#define MX_LPTIM2Freq_Value                     4000000
#define MX_USART1Freq_Value                     64000000
#define MX_LPTIM1Freq_Value                     4000000
#define MX_ADCFreq_Value                        64000000
#define MX_APBTimFreq_Value                     64000000
#define MX_SYSCLKFreq_VALUE1                    64
#define MX_SYSCLKFreq_VALUE2                    64
#define MX_USART2Freq_Value                     64000000
#define MX_I2C1Freq_Value                       64000000

/*-------------------------------- ADC1       --------------------------------*/

#define MX_ADC1                                 1

/* GPIO Configuration */

/* Pin PB1 */
#define MX_ADC1_IN9_Pin                         PB1
#define MX_ADC1_IN9_GPIOx                       GPIOB
#define MX_ADC1_IN9_GPIO_PuPd                   GPIO_NOPULL
#define MX_ADC1_IN9_GPIO_Pin                    GPIO_PIN_1
#define MX_ADC1_IN9_GPIO_Mode                   GPIO_MODE_ANALOG

/* Pin PB0 */
#define MX_ADC1_IN8_Pin                         PB0
#define MX_ADC1_IN8_GPIOx                       GPIOB
#define MX_ADC1_IN8_GPIO_PuPd                   GPIO_NOPULL
#define MX_ADC1_IN8_GPIO_Pin                    GPIO_PIN_0
#define MX_ADC1_IN8_GPIO_Mode                   GPIO_MODE_ANALOG

/* Pin PA7 */
#define MX_ADC1_IN7_Pin                         PA7
#define MX_ADC1_IN7_GPIOx                       GPIOA
#define MX_ADC1_IN7_GPIO_PuPd                   GPIO_NOPULL
#define MX_ADC1_IN7_GPIO_Pin                    GPIO_PIN_7
#define MX_ADC1_IN7_GPIO_Mode                   GPIO_MODE_ANALOG

/* Pin PA6 */
#define MX_ADC1_IN6_Pin                         PA6
#define MX_ADC1_IN6_GPIOx                       GPIOA
#define MX_ADC1_IN6_GPIO_PuPd                   GPIO_NOPULL
#define MX_ADC1_IN6_GPIO_Pin                    GPIO_PIN_6
#define MX_ADC1_IN6_GPIO_Mode                   GPIO_MODE_ANALOG

/* Pin PA5 */
#define MX_ADC1_IN5_Pin                         PA5
#define MX_ADC1_IN5_GPIOx                       GPIOA
#define MX_ADC1_IN5_GPIO_PuPd                   GPIO_NOPULL
#define MX_ADC1_IN5_GPIO_Pin                    GPIO_PIN_5
#define MX_ADC1_IN5_GPIO_Mode                   GPIO_MODE_ANALOG

/* Pin PC4 */
#define MX_ADC1_IN17_Pin                        PC4
#define MX_ADC1_IN17_GPIOx                      GPIOC
#define MX_ADC1_IN17_GPIO_PuPd                  GPIO_NOPULL
#define MX_ADC1_IN17_GPIO_Pin                   GPIO_PIN_4
#define MX_ADC1_IN17_GPIO_Mode                  GPIO_MODE_ANALOG

/* Pin PA4 */
#define MX_ADC1_IN4_Pin                         PA4
#define MX_ADC1_IN4_GPIOx                       GPIOA
#define MX_ADC1_IN4_GPIO_PuPd                   GPIO_NOPULL
#define MX_ADC1_IN4_GPIO_Pin                    GPIO_PIN_4
#define MX_ADC1_IN4_GPIO_Mode                   GPIO_MODE_ANALOG

/* Pin PC5 */
#define MX_ADC1_IN18_Pin                        PC5
#define MX_ADC1_IN18_GPIOx                      GPIOC
#define MX_ADC1_IN18_GPIO_PuPd                  GPIO_NOPULL
#define MX_ADC1_IN18_GPIO_Pin                   GPIO_PIN_5
#define MX_ADC1_IN18_GPIO_Mode                  GPIO_MODE_ANALOG

/* Pin PA3 */
#define MX_ADC1_IN3_Pin                         PA3
#define MX_ADC1_IN3_GPIOx                       GPIOA
#define MX_ADC1_IN3_GPIO_PuPd                   GPIO_NOPULL
#define MX_ADC1_IN3_GPIO_Pin                    GPIO_PIN_3
#define MX_ADC1_IN3_GPIO_Mode                   GPIO_MODE_ANALOG

/* Pin PA2 */
#define MX_ADC1_IN2_Pin                         PA2
#define MX_ADC1_IN2_GPIOx                       GPIOA
#define MX_ADC1_IN2_GPIO_PuPd                   GPIO_NOPULL
#define MX_ADC1_IN2_GPIO_Pin                    GPIO_PIN_2
#define MX_ADC1_IN2_GPIO_Mode                   GPIO_MODE_ANALOG

/* Pin PA1 */
#define MX_ADC1_IN1_Pin                         PA1
#define MX_ADC1_IN1_GPIOx                       GPIOA
#define MX_ADC1_IN1_GPIO_PuPd                   GPIO_NOPULL
#define MX_ADC1_IN1_GPIO_Pin                    GPIO_PIN_1
#define MX_ADC1_IN1_GPIO_Mode                   GPIO_MODE_ANALOG

/* Pin PA0 */
#define MX_ADC1_IN0_Pin                         PA0
#define MX_ADC1_IN0_GPIOx                       GPIOA
#define MX_ADC1_IN0_GPIO_PuPd                   GPIO_NOPULL
#define MX_ADC1_IN0_GPIO_Pin                    GPIO_PIN_0
#define MX_ADC1_IN0_GPIO_Mode                   GPIO_MODE_ANALOG

/*-------------------------------- DMA        --------------------------------*/

#define MX_DMA                                  1

/* NVIC Configuration */

/* NVIC DMA1_Channel1_IRQn */
#define MX_DMA1_Channel1_IRQn_interruptPremptionPriority 0
#define MX_DMA1_Channel1_IRQn_Subriority        0

/*-------------------------------- IWDG       --------------------------------*/

#define MX_IWDG                                 1

/* GPIO Configuration */

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/* Pin PA13 */
#define MX_SYS_SWDIO_Pin                        PA13

/* Pin PA14-BOOT0 */
#define MX_SYS_SWCLK_Pin                        PA14_BOOT0

/*-------------------------------- USART1     --------------------------------*/

#define MX_USART1                               1

#define MX_USART1_VM                            VM_ASYNC

/* GPIO Configuration */

/* Pin PB6 */
#define MX_USART1_TX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART1_TX_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_USART1_TX_GPIO_FM6                   __NULL
#define MX_USART1_TX_Pin                        PB6
#define MX_USART1_TX_GPIOx                      GPIOB
#define MX_USART1_TX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART1_TX_GPIO_Pin                   GPIO_PIN_6
#define MX_USART1_TX_GPIO_AF                    GPIO_AF0_USART1

/* Pin PB7 */
#define MX_USART1_RX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART1_RX_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_USART1_RX_Pin                        PB7
#define MX_USART1_RX_GPIOx                      GPIOB
#define MX_USART1_RX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART1_RX_GPIO_Pin                   GPIO_PIN_7
#define MX_USART1_RX_GPIO_AF                    GPIO_AF0_USART1
#define MX_USART1_RX_GPIO_FM7                   __NULL

/* DMA Configuration */

/* DMA USART1_TX */
#define MX_USART1_TX_DMA_Instance               DMA1_Channel1
#define MX_USART1_TX_DMA_Priority               DMA_PRIORITY_LOW
#define MX_USART1_TX_DMA_MemDataAlignment       DMA_MDATAALIGN_BYTE
#define MX_USART1_TX_DMA_Mode                   DMA_NORMAL
#define MX_USART1_TX_DMA_SyncRequestNumber      1
#define MX_USART1_TX_DMA_Request                DMA_REQUEST_USART1_TX
#define MX_USART1_TX_DMA_SyncPolarity           HAL_DMAMUX_SYNC_NO_EVENT
#define MX_USART1_TX_DMA_Direction              DMA_MEMORY_TO_PERIPH
#define MX_USART1_TX_DMA_SignalID               NONE
#define MX_USART1_TX_DMA_MemInc                 DMA_MINC_ENABLE
#define MX_USART1_TX_DMA_IpInstance
#define MX_USART1_TX_DMA_RequestNumber          1
#define MX_USART1_TX_DMA_EventEnable            DISABLE
#define MX_USART1_TX_DMA_SyncEnable             DISABLE
#define MX_USART1_TX_DMA_DMA_Handle
#define MX_USART1_TX_DMA_PeriphDataAlignment    DMA_PDATAALIGN_BYTE
#define MX_USART1_TX_DMA_Polarity               HAL_DMAMUX_REQ_GEN_RISING
#define MX_USART1_TX_DMA_SyncSignalID           NONE
#define MX_USART1_TX_DMA_PeriphInc              DMA_PINC_DISABLE

/* NVIC Configuration */

/* NVIC USART1_IRQn */
#define MX_USART1_IRQn_interruptPremptionPriority 0
#define MX_USART1_IRQn_Subriority               0

/*-------------------------------- USART2     --------------------------------*/

#define MX_USART2                               1

#define MX_USART2_VM                            VM_ASYNC

/* GPIO Configuration */

/* Pin PD5 */
#define MX_USART2_TX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART2_TX_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_USART2_TX_Pin                        PD5
#define MX_USART2_TX_GPIOx                      GPIOD
#define MX_USART2_TX_PinState                   GPIO_PIN_RESET
#define MX_USART2_TX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART2_TX_GPIO_Pin                   GPIO_PIN_5
#define MX_USART2_TX_GPIO_AF                    GPIO_AF0_USART2

/* Pin PD6 */
#define MX_USART2_RX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART2_RX_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_USART2_RX_Pin                        PD6
#define MX_USART2_RX_GPIOx                      GPIOD
#define MX_USART2_RX_PinState                   GPIO_PIN_RESET
#define MX_USART2_RX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART2_RX_GPIO_Pin                   GPIO_PIN_6
#define MX_USART2_RX_GPIO_AF                    GPIO_AF0_USART2

/* NVIC Configuration */

/* NVIC USART2_IRQn */
#define MX_USART2_IRQn_interruptPremptionPriority 0
#define MX_USART2_IRQn_Subriority               0

/*-------------------------------- USART4     --------------------------------*/

#define MX_USART4                               1

#define MX_USART4_VM                            VM_ASYNC

/* GPIO Configuration */

/* Pin PC10 */
#define MX_USART4_TX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART4_TX_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_USART4_TX_Pin                        PC10
#define MX_USART4_TX_GPIOx                      GPIOC
#define MX_USART4_TX_PinState                   GPIO_PIN_RESET
#define MX_USART4_TX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART4_TX_GPIO_Pin                   GPIO_PIN_10
#define MX_USART4_TX_GPIO_AF                    GPIO_AF1_USART4

/* Pin PC11 */
#define MX_USART4_RX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART4_RX_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_USART4_RX_Pin                        PC11
#define MX_USART4_RX_GPIOx                      GPIOC
#define MX_USART4_RX_PinState                   GPIO_PIN_RESET
#define MX_USART4_RX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART4_RX_GPIO_Pin                   GPIO_PIN_11
#define MX_USART4_RX_GPIO_AF                    GPIO_AF1_USART4

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

/* Pin PA11 [PA9] */
#define MX_PA11_PA9_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_PA11_PA9_Pin                         PA11_PA9
#define MX_PA11_PA9_GPIOx                       GPIOA
#define MX_PA11_PA9_PinState                    GPIO_PIN_RESET
#define MX_PA11_PA9_GPIO_PuPd                   GPIO_NOPULL
#define MX_PA11_PA9_GPIO_Pin                    GPIO_PIN_11
#define MX_PA11_PA9_GPIO_ModeDefaultOutputPP    GPIO_MODE_OUTPUT_PP

/* Pin PB3 */
#define MX_PB3_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PB3_Pin                              PB3
#define MX_PB3_GPIOx                            GPIOB
#define MX_PB3_PinState                         GPIO_PIN_RESET
#define MX_PB3_GPIO_PuPd                        GPIO_NOPULL
#define MX_PB3_GPIO_Pin                         GPIO_PIN_3
#define MX_PB3_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PB2 */
#define MX_PB2_Pin                              PB2
#define MX_PB2_GPIOx                            GPIOB
#define MX_PB2_GPIO_PuPd                        GPIO_NOPULL
#define MX_PB2_GPIO_Pin                         GPIO_PIN_2
#define MX_PB2_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PD4 */
#define MX_PD4_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PD4_Pin                              PD4
#define MX_PD4_GPIOx                            GPIOD
#define MX_PD4_PinState                         GPIO_PIN_RESET
#define MX_PD4_GPIO_PuPd                        GPIO_NOPULL
#define MX_PD4_GPIO_Pin                         GPIO_PIN_4
#define MX_PD4_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PB5 */
#define MX_PB5_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PB5_Pin                              PB5
#define MX_PB5_GPIOx                            GPIOB
#define MX_PB5_PinState                         GPIO_PIN_RESET
#define MX_PB5_GPIO_PuPd                        GPIO_NOPULL
#define MX_PB5_GPIO_Pin                         GPIO_PIN_5
#define MX_PB5_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PB4 */
#define MX_PB4_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PB4_Pin                              PB4
#define MX_PB4_GPIOx                            GPIOB
#define MX_PB4_PinState                         GPIO_PIN_RESET
#define MX_PB4_GPIO_PuPd                        GPIO_NOPULL
#define MX_PB4_GPIO_Pin                         GPIO_PIN_4
#define MX_PB4_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PD9 */
#define MX_PD9_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PD9_Pin                              PD9
#define MX_PD9_GPIOx                            GPIOD
#define MX_PD9_PinState                         GPIO_PIN_RESET
#define MX_PD9_GPIO_PuPd                        GPIO_NOPULL
#define MX_PD9_GPIO_Pin                         GPIO_PIN_9
#define MX_PD9_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PD8 */
#define MX_PD8_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PD8_Pin                              PD8
#define MX_PD8_GPIOx                            GPIOD
#define MX_PD8_PinState                         GPIO_PIN_RESET
#define MX_PD8_GPIO_PuPd                        GPIO_NOPULL
#define MX_PD8_GPIO_Pin                         GPIO_PIN_8
#define MX_PD8_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PB9 */
#define MX_PB9_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PB9_Pin                              PB9
#define MX_PB9_GPIOx                            GPIOB
#define MX_PB9_PinState                         GPIO_PIN_RESET
#define MX_PB9_GPIO_PuPd                        GPIO_NOPULL
#define MX_PB9_GPIO_Pin                         GPIO_PIN_9
#define MX_PB9_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP
#define MX_PB9_GPIO_FM9                         __NULL

/* Pin PB8 */
#define MX_PB8_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PB8_Pin                              PB8
#define MX_PB8_GPIOx                            GPIOB
#define MX_PB8_PinState                         GPIO_PIN_RESET
#define MX_PB8_GPIO_PuPd                        GPIO_NOPULL
#define MX_PB8_GPIO_Pin                         GPIO_PIN_8
#define MX_PB8_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP
#define MX_PB8_GPIO_FM8                         __NULL

/* Pin PC15-OSC32_OUT (PC15) */
#define MX_PC15_OSC32_OUT_PC15_GPIO_Speed       GPIO_SPEED_FREQ_LOW
#define MX_PC15_OSC32_OUT_PC15_Pin              PC15_OSC32_OUT_PC15
#define MX_PC15_OSC32_OUT_PC15_GPIOx            GPIOC
#define MX_PC15_OSC32_OUT_PC15_PinState         GPIO_PIN_RESET
#define MX_PC15_OSC32_OUT_PC15_GPIO_PuPd        GPIO_NOPULL
#define MX_PC15_OSC32_OUT_PC15_GPIO_Pin         GPIO_PIN_15
#define MX_PC15_OSC32_OUT_PC15_GPIO_ModeDefaultOutputPP GPIO_MODE_OUTPUT_PP

/* Pin PC0 */
#define MX_PC0_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PC0_Pin                              PC0
#define MX_PC0_GPIOx                            GPIOC
#define MX_PC0_PinState                         GPIO_PIN_RESET
#define MX_PC0_GPIO_PuPd                        GPIO_NOPULL
#define MX_PC0_GPIO_Pin                         GPIO_PIN_0
#define MX_PC0_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PC2 */
#define MX_PC2_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PC2_Pin                              PC2
#define MX_PC2_GPIOx                            GPIOC
#define MX_PC2_PinState                         GPIO_PIN_RESET
#define MX_PC2_GPIO_PuPd                        GPIO_NOPULL
#define MX_PC2_GPIO_Pin                         GPIO_PIN_2
#define MX_PC2_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PC1 */
#define MX_PC1_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PC1_Pin                              PC1
#define MX_PC1_GPIOx                            GPIOC
#define MX_PC1_PinState                         GPIO_PIN_RESET
#define MX_PC1_GPIO_PuPd                        GPIO_NOPULL
#define MX_PC1_GPIO_Pin                         GPIO_PIN_1
#define MX_PC1_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PC3 */
#define MX_PC3_Pin                              PC3
#define MX_PC3_GPIOx                            GPIOC
#define MX_PC3_GPIO_PuPd                        GPIO_NOPULL
#define MX_PC3_GPIO_Pin                         GPIO_PIN_3
#define MX_PC3_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PC6 */
#define MX_PC6_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PC6_Pin                              PC6
#define MX_PC6_GPIOx                            GPIOC
#define MX_PC6_PinState                         GPIO_PIN_RESET
#define MX_PC6_GPIO_PuPd                        GPIO_NOPULL
#define MX_PC6_GPIO_Pin                         GPIO_PIN_6
#define MX_PC6_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PC8 */
#define MX_PC8_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PC8_Pin                              PC8
#define MX_PC8_GPIOx                            GPIOC
#define MX_PC8_PinState                         GPIO_PIN_RESET
#define MX_PC8_GPIO_PuPd                        GPIO_NOPULL
#define MX_PC8_GPIO_Pin                         GPIO_PIN_8
#define MX_PC8_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PC7 */
#define MX_PC7_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PC7_Pin                              PC7
#define MX_PC7_GPIOx                            GPIOC
#define MX_PC7_PinState                         GPIO_PIN_RESET
#define MX_PC7_GPIO_PuPd                        GPIO_NOPULL
#define MX_PC7_GPIO_Pin                         GPIO_PIN_7
#define MX_PC7_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PA8 */
#define MX_PA8_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PA8_Pin                              PA8
#define MX_PA8_GPIOx                            GPIOA
#define MX_PA8_PinState                         GPIO_PIN_RESET
#define MX_PA8_GPIO_PuPd                        GPIO_NOPULL
#define MX_PA8_GPIO_Pin                         GPIO_PIN_8
#define MX_PA8_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PA12 [PA10] */
#define MX_PA12_PA10_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_PA12_PA10_Pin                        PA12_PA10
#define MX_PA12_PA10_GPIOx                      GPIOA
#define MX_PA12_PA10_PinState                   GPIO_PIN_RESET
#define MX_PA12_PA10_GPIO_PuPd                  GPIO_NOPULL
#define MX_PA12_PA10_GPIO_Pin                   GPIO_PIN_12
#define MX_PA12_PA10_GPIO_ModeDefaultOutputPP   GPIO_MODE_OUTPUT_PP

/* Pin PC9 */
#define MX_PC9_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PC9_Pin                              PC9
#define MX_PC9_GPIOx                            GPIOC
#define MX_PC9_PinState                         GPIO_PIN_RESET
#define MX_PC9_GPIO_PuPd                        GPIO_NOPULL
#define MX_PC9_GPIO_Pin                         GPIO_PIN_9
#define MX_PC9_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PA9 */
#define MX_PA9_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PA9_Pin                              PA9
#define MX_PA9_GPIOx                            GPIOA
#define MX_PA9_PinState                         GPIO_PIN_RESET
#define MX_PA9_GPIO_PuPd                        GPIO_NOPULL
#define MX_PA9_GPIO_Pin                         GPIO_PIN_9
#define MX_PA9_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP
#define MX_PA9_GPIO_FMPA9                       __NULL

/* Pin PF1-OSC_OUT (PF1) */
#define MX_PF1_OSC_OUT_PF1_GPIO_Speed           GPIO_SPEED_FREQ_LOW
#define MX_PF1_OSC_OUT_PF1_Pin                  PF1_OSC_OUT_PF1
#define MX_PF1_OSC_OUT_PF1_GPIOx                GPIOF
#define MX_PF1_OSC_OUT_PF1_PinState             GPIO_PIN_RESET
#define MX_PF1_OSC_OUT_PF1_GPIO_PuPd            GPIO_NOPULL
#define MX_PF1_OSC_OUT_PF1_GPIO_Pin             GPIO_PIN_1
#define MX_PF1_OSC_OUT_PF1_GPIO_ModeDefaultOutputPP GPIO_MODE_OUTPUT_PP

/* Pin PC13 */
#define MX_PC13_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PC13_Pin                             PC13
#define MX_PC13_GPIOx                           GPIOC
#define MX_PC13_PinState                        GPIO_PIN_RESET
#define MX_PC13_GPIO_PuPd                       GPIO_NOPULL
#define MX_PC13_GPIO_Pin                        GPIO_PIN_13
#define MX_PC13_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PB14 */
#define MX_PB14_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PB14_Pin                             PB14
#define MX_PB14_GPIOx                           GPIOB
#define MX_PB14_PinState                        GPIO_PIN_RESET
#define MX_PB14_GPIO_PuPd                       GPIO_NOPULL
#define MX_PB14_GPIO_Pin                        GPIO_PIN_14
#define MX_PB14_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PA15 */
#define MX_PA15_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PA15_Pin                             PA15
#define MX_PA15_GPIOx                           GPIOA
#define MX_PA15_PinState                        GPIO_PIN_RESET
#define MX_PA15_GPIO_PuPd                       GPIO_NOPULL
#define MX_PA15_GPIO_Pin                        GPIO_PIN_15
#define MX_PA15_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PC12 */
#define MX_PC12_Pin                             PC12
#define MX_PC12_GPIOx                           GPIOC
#define MX_PC12_GPIO_PuPd                       GPIO_NOPULL
#define MX_PC12_GPIO_Pin                        GPIO_PIN_12
#define MX_PC12_GPIO_Mode                       GPIO_MODE_INPUT

/* Pin PB13 */
#define MX_PB13_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PB13_Pin                             PB13
#define MX_PB13_GPIOx                           GPIOB
#define MX_PB13_PinState                        GPIO_PIN_RESET
#define MX_PB13_GPIO_PuPd                       GPIO_NOPULL
#define MX_PB13_GPIO_Pin                        GPIO_PIN_13
#define MX_PB13_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PB15 */
#define MX_PB15_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PB15_Pin                             PB15
#define MX_PB15_GPIOx                           GPIOB
#define MX_PB15_PinState                        GPIO_PIN_RESET
#define MX_PB15_GPIO_PuPd                       GPIO_NOPULL
#define MX_PB15_GPIO_Pin                        GPIO_PIN_15
#define MX_PB15_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PB10 */
#define MX_PB10_Pin                             PB10
#define MX_PB10_GPIOx                           GPIOB
#define MX_PB10_GPIO_PuPd                       GPIO_NOPULL
#define MX_PB10_GPIO_Pin                        GPIO_PIN_10
#define MX_PB10_GPIO_Mode                       GPIO_MODE_INPUT

/* Pin PA10 */
#define MX_PA10_Pin                             PA10
#define MX_PA10_GPIOx                           GPIOA
#define MX_PA10_GPIO_PuPd                       GPIO_NOPULL
#define MX_PA10_GPIO_Pin                        GPIO_PIN_10
#define MX_PA10_GPIO_Mode                       GPIO_MODE_INPUT

/* Pin PB12 */
#define MX_PB12_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PB12_Pin                             PB12
#define MX_PB12_GPIOx                           GPIOB
#define MX_PB12_PinState                        GPIO_PIN_RESET
#define MX_PB12_GPIO_PuPd                       GPIO_NOPULL
#define MX_PB12_GPIO_Pin                        GPIO_PIN_12
#define MX_PB12_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PF0-OSC_IN (PF0) */
#define MX_PF0_OSC_IN_PF0_GPIO_Speed            GPIO_SPEED_FREQ_LOW
#define MX_PF0_OSC_IN_PF0_Pin                   PF0_OSC_IN_PF0
#define MX_PF0_OSC_IN_PF0_GPIOx                 GPIOF
#define MX_PF0_OSC_IN_PF0_PinState              GPIO_PIN_RESET
#define MX_PF0_OSC_IN_PF0_GPIO_PuPd             GPIO_NOPULL
#define MX_PF0_OSC_IN_PF0_GPIO_Pin              GPIO_PIN_0
#define MX_PF0_OSC_IN_PF0_GPIO_ModeDefaultOutputPP GPIO_MODE_OUTPUT_PP

/* Pin PB11 */
#define MX_PB11_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PB11_Pin                             PB11
#define MX_PB11_GPIOx                           GPIOB
#define MX_PB11_PinState                        GPIO_PIN_RESET
#define MX_PB11_GPIO_PuPd                       GPIO_NOPULL
#define MX_PB11_GPIO_Pin                        GPIO_PIN_11
#define MX_PB11_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PD1 */
#define MX_PD1_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PD1_Pin                              PD1
#define MX_PD1_GPIOx                            GPIOD
#define MX_PD1_PinState                         GPIO_PIN_RESET
#define MX_PD1_GPIO_PuPd                        GPIO_NOPULL
#define MX_PD1_GPIO_Pin                         GPIO_PIN_1
#define MX_PD1_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PD0 */
#define MX_PD0_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PD0_Pin                              PD0
#define MX_PD0_GPIOx                            GPIOD
#define MX_PD0_PinState                         GPIO_PIN_RESET
#define MX_PD0_GPIO_PuPd                        GPIO_NOPULL
#define MX_PD0_GPIO_Pin                         GPIO_PIN_0
#define MX_PD0_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PD3 */
#define MX_PD3_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PD3_Pin                              PD3
#define MX_PD3_GPIOx                            GPIOD
#define MX_PD3_PinState                         GPIO_PIN_RESET
#define MX_PD3_GPIO_PuPd                        GPIO_NOPULL
#define MX_PD3_GPIO_Pin                         GPIO_PIN_3
#define MX_PD3_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PD2 */
#define MX_PD2_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PD2_Pin                              PD2
#define MX_PD2_GPIOx                            GPIOD
#define MX_PD2_PinState                         GPIO_PIN_RESET
#define MX_PD2_GPIO_PuPd                        GPIO_NOPULL
#define MX_PD2_GPIO_Pin                         GPIO_PIN_2
#define MX_PD2_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

#endif  /* __MX_DEVICE_H */

